# Site settings
title: FSX By GRC
motto: 
email: haonancx@outlook.com
description: 关人潮,前端工程师,个人博客,HTML5,技术博客,CSS3,移动开发,vue,angular,react,Jquery,面试前端
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://haonancx.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  Haonancx
pygments: true
# Outputting
permalink: pretty
paginate: 5
paginate_path: /page/:num
timezone: 

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
